version: '3'
services:
  api: 
    image: 'node:6-alpine'
    env_file:
     - ./.env
  # Uncomment the lines bellow for using a non-cloud database
  #postgres:
    #container_name: postgres-db
    #image: postgres
    #restart: always
    #ports:
      #- 5432:5432
    #environment:
       #POSTGRES_DB: ${POSTGRES_DATABASE}
       #POSTGRES_USER: ${POSTGRES_USER}
       #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #volumes:
      #- ./volumes/home:/home
      #- ./volumes/home/work:/work
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        # set ssl property in case you're using a cloud based db
        # ssl: true
        databases:
          default:
            connector: ${DATABASE_CONNECTOR}
            host: ${POSTGRES_HOST}
            port: '5432'
            ssl: true
            database: ${POSTGRES_DATABASE}
            schema: ${POSTGRES_SCHEMA}
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            migrations: true