version: '3'
services:
  api: 
    image: 'node:6-alpine'
    env_file:
     - ./.env
  postgres:
    container_name: postgres-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
       POSTGRES_DB: pg_prisma
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/home:/home
      - ./volumes/home/work:/work
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ${HOST}
            port: 5432
            database: ${DATABASE}
            schema: schema.graphql
            user: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
            migrations: true